module RubyGameHub
  class ChatterBox
    module Proto
      # HUB
      HUB_GREETING = "HI"
      HUB_PUBLIC_KEY = "THANK YOU HERE IS MY PUBLIC KEY"
      HUB_API_PUBLIC_KEY_FAILED_VERIFICATION = "I DONT KNOW YOU."
      HUB_SHUTDOWN = "GOODBYE."

      # API
      API_GREETING = "HELLO"
      API_PUBLIC_KEY = "HERE IS MY PUBLIC KEY"
      API_CONFIRM_RECEIVE_HUB_PUBLIC_KEY = "GOT IT."
      API_HUB_PUBLIC_KEY_FAILED_VERIFICATION = "I CANT VERIFIY YOU."
      API_DISCONNECT = "BYE."
    end
  end
end
